/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubRouteImport } from './routes/_github'
import { Route as FameRouteImport } from './routes/fame'
import { Route as GithubManageRouteImport } from './routes/_github/manage'
import { Route as GithubTransferRouteImport } from './routes/_github/transfer'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/_github',
  getParentRoute: () => rootRouteImport,
} as any)
const FameRoute = FameRouteImport.update({
  id: '/fame',
  path: '/fame',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubManageRoute = GithubManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => GithubRoute,
} as any)
const GithubTransferRoute = GithubTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => GithubRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fame': typeof FameRoute
  '/manage': typeof GithubManageRoute
  '/transfer': typeof GithubTransferRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fame': typeof FameRoute
  '/manage': typeof GithubManageRoute
  '/transfer': typeof GithubTransferRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_github': typeof GithubRouteWithChildren
  '/fame': typeof FameRoute
  '/_github/manage': typeof GithubManageRoute
  '/_github/transfer': typeof GithubTransferRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fame' | '/manage' | '/transfer' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fame' | '/manage' | '/transfer' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_github'
    | '/fame'
    | '/_github/manage'
    | '/_github/transfer'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubRoute: typeof GithubRouteWithChildren
  FameRoute: typeof FameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_github': {
      id: '/_github'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fame': {
      id: '/fame'
      path: '/fame'
      fullPath: '/fame'
      preLoaderRoute: typeof FameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_github/manage': {
      id: '/_github/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof GithubManageRouteImport
      parentRoute: typeof GithubRoute
    }
    '/_github/transfer': {
      id: '/_github/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof GithubTransferRouteImport
      parentRoute: typeof GithubRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GithubRouteChildren {
  GithubManageRoute: typeof GithubManageRoute
  GithubTransferRoute: typeof GithubTransferRoute
}

const GithubRouteChildren: GithubRouteChildren = {
  GithubManageRoute: GithubManageRoute,
  GithubTransferRoute: GithubTransferRoute,
}

const GithubRouteWithChildren =
  GithubRoute._addFileChildren(GithubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubRoute: GithubRouteWithChildren,
  FameRoute: FameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
